# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/NikithaShravan/Downloads/BOW-Slic_EDGE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/NikithaShravan/Downloads/BOW-Slic_EDGE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/NikithaShravan/Downloads/BOW-Slic_EDGE/CMakeFiles /Users/NikithaShravan/Downloads/BOW-Slic_EDGE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/NikithaShravan/Downloads/BOW-Slic_EDGE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_bow_slic

# Build rule for target.
test_bow_slic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bow_slic
.PHONY : test_bow_slic

# fast build rule for target.
test_bow_slic/fast:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/build
.PHONY : test_bow_slic/fast

src/bow_slic.o: src/bow_slic.cpp.o

.PHONY : src/bow_slic.o

# target to build an object file
src/bow_slic.cpp.o:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/bow_slic.cpp.o
.PHONY : src/bow_slic.cpp.o

src/bow_slic.i: src/bow_slic.cpp.i

.PHONY : src/bow_slic.i

# target to preprocess a source file
src/bow_slic.cpp.i:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/bow_slic.cpp.i
.PHONY : src/bow_slic.cpp.i

src/bow_slic.s: src/bow_slic.cpp.s

.PHONY : src/bow_slic.s

# target to generate assembly for a file
src/bow_slic.cpp.s:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/bow_slic.cpp.s
.PHONY : src/bow_slic.cpp.s

src/debugging_functions.o: src/debugging_functions.cpp.o

.PHONY : src/debugging_functions.o

# target to build an object file
src/debugging_functions.cpp.o:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/debugging_functions.cpp.o
.PHONY : src/debugging_functions.cpp.o

src/debugging_functions.i: src/debugging_functions.cpp.i

.PHONY : src/debugging_functions.i

# target to preprocess a source file
src/debugging_functions.cpp.i:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/debugging_functions.cpp.i
.PHONY : src/debugging_functions.cpp.i

src/debugging_functions.s: src/debugging_functions.cpp.s

.PHONY : src/debugging_functions.s

# target to generate assembly for a file
src/debugging_functions.cpp.s:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/debugging_functions.cpp.s
.PHONY : src/debugging_functions.cpp.s

src/oversegmentation.o: src/oversegmentation.cpp.o

.PHONY : src/oversegmentation.o

# target to build an object file
src/oversegmentation.cpp.o:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/oversegmentation.cpp.o
.PHONY : src/oversegmentation.cpp.o

src/oversegmentation.i: src/oversegmentation.cpp.i

.PHONY : src/oversegmentation.i

# target to preprocess a source file
src/oversegmentation.cpp.i:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/oversegmentation.cpp.i
.PHONY : src/oversegmentation.cpp.i

src/oversegmentation.s: src/oversegmentation.cpp.s

.PHONY : src/oversegmentation.s

# target to generate assembly for a file
src/oversegmentation.cpp.s:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/oversegmentation.cpp.s
.PHONY : src/oversegmentation.cpp.s

src/test_bow_slic.o: src/test_bow_slic.cpp.o

.PHONY : src/test_bow_slic.o

# target to build an object file
src/test_bow_slic.cpp.o:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/test_bow_slic.cpp.o
.PHONY : src/test_bow_slic.cpp.o

src/test_bow_slic.i: src/test_bow_slic.cpp.i

.PHONY : src/test_bow_slic.i

# target to preprocess a source file
src/test_bow_slic.cpp.i:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/test_bow_slic.cpp.i
.PHONY : src/test_bow_slic.cpp.i

src/test_bow_slic.s: src/test_bow_slic.cpp.s

.PHONY : src/test_bow_slic.s

# target to generate assembly for a file
src/test_bow_slic.cpp.s:
	$(MAKE) -f CMakeFiles/test_bow_slic.dir/build.make CMakeFiles/test_bow_slic.dir/src/test_bow_slic.cpp.s
.PHONY : src/test_bow_slic.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test_bow_slic"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/bow_slic.o"
	@echo "... src/bow_slic.i"
	@echo "... src/bow_slic.s"
	@echo "... src/debugging_functions.o"
	@echo "... src/debugging_functions.i"
	@echo "... src/debugging_functions.s"
	@echo "... src/oversegmentation.o"
	@echo "... src/oversegmentation.i"
	@echo "... src/oversegmentation.s"
	@echo "... src/test_bow_slic.o"
	@echo "... src/test_bow_slic.i"
	@echo "... src/test_bow_slic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

